### ISSUE TITLE
License

### ISSUE THREAD

**Issue by AliKarpuzoglu** [sergeim19/SP-MCTS#1]
Hey,
I would love to reuse parts of your code for a student project. Do you have any (open) license in mind? Maybe MIT?

**Comment by sergeim19** [comment]
License created. Feel free to use it how you like but it really isn't validated code and it's been too long for me to want to go back and check. Some parts may even be incomplete (I don't remember).

**Comment by AliKarpuzoglu** [comment]
thanks, I'll try it out and if I find sth I'll report back
